export const screenUrls = {
    Dashboard: "/dashboard",
    HoSo: "/hoso",
    Account: "/account",
    BaoCao: "/bao-cao",
    BaoCaoCreate: "/bao-cao/create",
    BaoCaoDetail: "/bao-cao/:id",
    BaoCaoChiTiet: "/bao-cao/chi-tiet/:id",
    BaoCaoThietKe: "/bao-cao/chi-tiet/:id/thiet-ke",
    DonViConTrucThuoc: "/don-vi-con-truc-thuoc",
    DonViConTrucThuocDetail: "/don-vi-con-truc-thuoc/:accountId",
    DonViConTrucThuocChiTietBaoCao: "/don-vi-con-truc-thuoc/:accountId/chi-tiet-bao-cao/:baoCaoId",
    GiaoBaoCao: "/giao-bao-cao",
    CauHinhDonViNhanBaoCao: "/cau-hinh-don-vi-nhan-baocao",
    ThietKeKyBaoCao: "/thiet-ke-ky-bao-cao",
    ThongTinCaNhan: "/thong-tin-ca-nhan",
    DoiMatKhau: "/doi-mat-khau",
    CongViecCuaToi: "/cong-viec-cua-toi",
    HoSoTienDo: "/ho-so-tien-do",
    ThongBao: "/thong-bao",
    BanDo: "/ban-do",
    ThongKe: "/thong-ke",
};